language: python
python:
  - "3.6"
install:
  - pip install SPARQLwrapper pronto
  - pip install pubrunner
script:
   - mkdir -p umls/2020AA
   - touch umls/2020AA/META/MRCONSO.RRF
   - sh generate_all.sh
