import argparse
from googlesearch import search
import json
import time
import os
import sys

#for url in search('egfr gene', stop=10):
#	print(url)

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description='Do a lot of Google searches to identify misnamed genes')
	parser.add_argument('--genes',type=str,required=True,help='Gene list generated by Biowordlists')
	parser.add_argument('--searchResults',type=str,required=True,help='Output JSON file with search results')
	args = parser.parse_args()

	genes = set()
	with open(args.genes) as f:
		for line in f:
			gene_hugo_id,name,terms,gene_entrez_id = line.strip('\n').split('\t')
			terms = terms.split('|')
			genes.update(terms)

	genes = sorted(list(genes))
	print("%d gene names loaded" % len(genes))

	results = {}
	if os.path.isfile(args.searchResults):
		with open(args.searchResults) as f:
			results = json.load(f)
		print("Continuing with %d genes already processed" % len(results))

	for i,gene in enumerate(genes):
		if gene in results and len(results[gene]) > 0:
			continue

		urls = list(search('%s gene' % gene, stop=10))
		results[gene] = urls
		if len(urls) > 0:
			with open(args.searchResults,'w') as outF:
				json.dump(results,outF,indent=2,sort_keys=True)
		print("%s (%d/%d) - %d URLs" % (gene,i+1,len(genes),len(urls)))
		sys.stdout.flush()
		#break


		time.sleep(5)

